// Brand Colors
export const COLORS = {
  deepForest: '#0F231B',
  forest2: '#132E24',
  forest3: '#1B3D2F',
  softOchre: '#C5A67A',
  goldLight: '#D9C19E',
  goldDeep: '#A68A62',
  ivory: '#FDFBF6',
  ivory2: '#F7F0E6',
  cream: '#EFE6D5',
  parchment: '#F8F4EA',
  stone: '#A69E93',
  charcoal: '#171D1A',
};

// Three.js colors (hex numbers)
export const THREE_COLORS = {
  deepForest: 0x0F231B,
  forest2: 0x132E24,
  softOchre: 0xC5A67A,
  goldLight: 0xD9C19E,
  parchment: 0xFDFBF6,
  stone: 0xA69E93,
  charcoal: 0x171D1A,
  black: 0x000000,
  white: 0xffffff,
};

// Navigation
export const NAV_ITEMS = [
  { label: 'Services', href: '#services' },
  { label: 'Work', href: '#work' },
  { label: 'About', href: '#about' },
  { label: 'Process', href: '#process' },
  { label: 'Why Us', href: '#why' },
  { label: 'Contact', href: '#contact' },
];

// Contact & Booking Details
export const CONTACT_INFO = {
  phone: '+91 94094 10260',
  whatsappNumber: '919409410260',
  calBookingUrl: 'https://cal.com/skalorix/30min',
  email: 'hello@skalorix.com',
  location: 'Surat, Gujarat, India',
};

// Services (6 Core Disciplines with exact 2026 packages, pricing and deliverables)
export const SERVICES = [
  {
    num: '01',
    slug: 'web-development',
    name: 'Website Development',
    tagline: 'Your Business Deserves a Powerful Online Home',
    desc: 'Modern, fast & conversion-focused websites built to grow your business.',
    startingPrice: '₹12,999',
    timeline: '5 – 7 Days Delivery',
    metricsHighlight: 'Sub-2s Load Times & 100% Mobile Optimized',
    tags: ['React / Next.js', 'B2B RFQ Portal', 'E-Commerce', 'Speed Optimization', 'SEO Architecture', 'Clean UI/UX'],
    capabilities: ['Responsive Web Design', 'Dynamic CMS Showcase', 'B2B RFQ Enquiry Portal', 'E-Commerce Storefronts', 'Payment Gateways', 'Speed Optimization'],
    coreDeliverables: [
      '1–5 or 10–15 high-performance responsive pages with clean code',
      'B2B Request-For-Quote (RFQ) enquiry portal with database capture',
      'Full E-Commerce storefront (Shopify / Next.js / WooCommerce) up to 100 products',
      'Automated Shiprocket / Delhivery courier sync & WhatsApp order tracking',
    ],
    image: '/assets/services/service-web-development.jpg',
    packages: [
      {
        name: 'Starter Web',
        badge: 'BEST FOR SMALL BUSINESSES',
        tagline: 'FOUNDATION • QUICK LAUNCH',
        price: '₹12,999',
        period: 'One-time investment',
        idealFor: 'Local stores, clinics, traders, consultants',
        timeline: '5–7 Days',
        features: [
          '1–5 High-performance responsive pages',
          'Home, About, Services/Products, Gallery, Contact',
          'WhatsApp Click-to-Chat & enquiry form with instant email alerts',
          'Google Maps embedding, SSL security, mobile speed optimization',
          'Basic On-Page SEO setup',
          'Meta tags, sitemap, Google Search Console indexing',
        ],
      },
      {
        name: 'Professional Web',
        badge: 'BEST FOR GROWING BRANDS',
        popular: true,
        tagline: 'GROWTH • CMS & LEAD GEN',
        price: '₹24,999',
        period: 'One-time investment',
        idealFor: 'Textile mills, diamond exporters, factories',
        timeline: '10–14 Days',
        features: [
          'Up to 10–15 custom designed pages or dynamic CMS product showcase',
          'B2B Request-For-Quote (RFQ) enquiry portal with direct customer database capture',
          'Speed optimization (sub-2s load time), schema markup, blog/news section',
          'Google Analytics 4 setup, social media feed sync',
          '30 days post-launch support',
        ],
      },
      {
        name: 'Premium E-Commerce',
        badge: 'BEST FOR ONLINE BRANDS',
        tagline: 'FULL SCALE • E-COMMERCE',
        price: '₹44,999+',
        period: 'One-time investment',
        idealFor: 'Saree/Kurti brands, jewelry, D2C portals',
        timeline: '20–25 Days',
        features: [
          'Complete E-Commerce storefront (Shopify / Next.js / WooCommerce) to 100 products',
          'Payment gateway integration: Razorpay, PhonePe, Cashfree, COD verification engine',
          'Automated Shiprocket / Delhivery courier sync + automated WhatsApp order tracking',
          'Abandoned cart recovery flows, coupon discount engine',
          'Product reviews & priority support',
        ],
      },
    ],
  },
  {
    num: '02',
    slug: 'software-development',
    name: 'Custom Software Development',
    tagline: 'Turning Your Ideas Into Powerful Solutions',
    desc: 'Tailored software solutions to automate, simplify and scale your business.',
    startingPrice: '₹59,999+',
    timeline: '20 – 30 Days Delivery',
    metricsHighlight: '100% Scalable, Secure & Custom Built',
    tags: ['Custom Architecture', 'ERP & CRM Systems', 'Role-Based Access', 'API Integrations', 'Post-Launch Support', 'Clean DB'],
    capabilities: ['Custom Architecture', 'Admin Dashboards', 'Role-Based Access Control', 'ERP & CRM Integration', 'Automated Alerts', 'QA & Stress-Testing'],
    coreDeliverables: [
      'Requirement discussion, UI/UX wireframing & full-stack development',
      'Up to 5 to 15+ custom business modules & admin panels',
      'Database design, query speed optimization & automated alerts (Email/SMS/WhatsApp)',
      'Integration suite (ERP, CRM, Tally, SAP, external APIs) & dedicated support',
    ],
    image: '/assets/services/service-software-development.jpg',
    packages: [
      {
        name: 'Basic Software',
        badge: 'BEST FOR SMALL BUSINESSES',
        tagline: 'FOUNDATION • 5 CORE MODULES',
        price: '₹59,999+',
        period: '/ project',
        idealFor: 'Small businesses & simple internal systems',
        timeline: '20–30 Days',
        features: [
          'Requirement discussion & UI/UX wireframing',
          'Up to 5 core functional modules',
          'Full-stack Frontend & Backend development',
          'Database integration, login & auth engine',
          'Intuitive admin panel with summary reports',
          'Deployment support & 30 days assistance',
        ],
      },
      {
        name: 'Business Software',
        badge: 'BEST FOR GROWING BUSINESSES',
        popular: true,
        tagline: 'GROWTH • 10–15 CUSTOM MODULES',
        price: '₹1,49,999+',
        period: '/ project',
        idealFor: 'Growing businesses needing custom workflows',
        timeline: '45–60 Days',
        features: [
          'Detailed requirement analysis & tailored UI/UX',
          'Up to 10–15 customized business modules',
          'Database design & query speed optimization',
          'Role-based access control & external API sync',
          'Automated alerts (Email / SMS / WhatsApp)',
          'Advanced dashboards & 60 days post-launch support',
        ],
      },
      {
        name: 'Enterprise Solution',
        badge: 'BEST FOR ESTABLISHED ENTITIES',
        tagline: 'SCALE • ENTERPRISE ARCHITECTURE',
        price: '₹3,00,000+',
        period: '/ project',
        idealFor: 'Large organizations with complex operations',
        timeline: '60–90 Days',
        features: [
          'Enterprise-grade custom system architecture',
          'Unlimited modules & multi-branch architecture',
          'Integration suite (ERP, CRM, Tally, SAP, APIs)',
          'High-security protocols & strict role governance',
          'Full stress-testing, QA suites & load balancing',
          'Dedicated project lead & priority ongoing support',
        ],
      },
    ],
  },
  {
    num: '03',
    slug: 'search-engine-optimization',
    name: 'Search Engine Optimization (SEO)',
    tagline: 'Get Found. Get Clients. Grow Faster.',
    desc: 'Data-driven SEO strategies to increase your visibility, traffic and sales.',
    startingPrice: '₹7,999 / mo',
    timeline: 'Monthly Retainer Sprint',
    metricsHighlight: 'Higher Rankings & Real Business Growth',
    tags: ['Technical SEO', 'Keyword Strategy', 'Content SEO', 'Link Building', 'Local SEO', 'Google Search Console'],
    capabilities: ['Technical SEO Optimization', 'Keyword Research', 'On-Page SEO', 'Content Strategy & Blogs', 'Google Business Profile', 'Ethical Backlink Strategy'],
    coreDeliverables: [
      'Keyword research up to 20–100 high-intent keywords',
      'On-page SEO up to 5–30 pages & technical SEO optimization',
      'Content strategy & SEO content (2–4 blog articles/month)',
      'Google Business Profile, local SEO, schema markup & monthly insights',
    ],
    image: '/assets/services/service-seo.jpg',
    packages: [
      {
        name: 'Starter',
        badge: 'BEST FOR NEW BUSINESSES',
        tagline: 'FOUNDATION • LOCAL VISIBILITY',
        price: '₹7,999',
        period: '/ month',
        idealFor: 'New websites & small local businesses',
        timeline: 'Monthly SEO Retainer',
        features: [
          'Keyword research up to 20 keywords',
          'On-page SEO up to 5 pages',
          'Meta titles & descriptions',
          'Basic technical SEO setup',
          'XML sitemap & Search Console setup',
          'Basic competitor analysis',
          'Monthly performance report',
          'Email / WhatsApp support',
        ],
      },
      {
        name: 'Professional',
        badge: 'BEST FOR GROWING BUSINESSES',
        popular: true,
        tagline: 'GROWTH • CONTENT • TECHNICAL SEO',
        price: '₹14,999',
        period: '/ month',
        idealFor: 'Growing businesses wanting consistent organic growth',
        timeline: 'Monthly SEO Retainer',
        features: [
          'Keyword research up to 50 keywords',
          'On-page SEO up to 15 pages',
          'Technical SEO optimization',
          'Content strategy & SEO content (2 blogs/month)',
          'Google Business Profile optimization',
          'Image optimization & alt tags',
          'Competitor analysis',
          'Monthly insights report',
          'Priority support (Email / WhatsApp / Call)',
        ],
      },
      {
        name: 'Premium',
        badge: 'BEST FOR ESTABLISHED BRANDS',
        tagline: 'AUTHORITY • SCALE • ADVANCED SEO',
        price: '₹29,999',
        period: '/ month',
        idealFor: 'Competitive industries & ambitious multi-location brands',
        timeline: 'Monthly SEO Retainer',
        features: [
          'Keyword research up to 100 keywords',
          'On-page SEO up to 30 pages',
          'Advanced technical SEO',
          'Content strategy & SEO content (4 blogs/month)',
          'Local & multi-location SEO',
          'High-quality ethical backlink strategy',
          'Schema & structured data optimization',
          'Detailed competitor analysis',
          'Monthly insights report',
          'Dedicated account manager',
        ],
      },
    ],
  },
  {
    num: '04',
    slug: 'creative-services',
    name: 'Creative Design Services',
    tagline: 'Designs That Make You Memorable.',
    desc: 'From social media to brand identity, we create visuals that connect, engage and convert.',
    startingPrice: '₹4,999 / mo',
    timeline: '2 – 3 Days Delivery',
    metricsHighlight: 'Bespoke Visuals & Brand Consistency',
    tags: ['Social Media Design', 'Brand Identity', 'Print Design', 'Digital Creatives', 'Marketing Materials', 'Reel Editing'],
    capabilities: ['Social Media Creatives', 'Carousels & Stories', 'Reel Editing & Covers', 'Brochures & Flyers', 'Logo & Brand Identity', 'Ad Creatives'],
    coreDeliverables: [
      'Up to 10 to 50 custom designs per month on monthly retainer',
      'Social posts, carousels, stories, festival & campaign creatives',
      'Reel covers, thumbnails, reel editing & motion graphics',
      'Brochures, flyers, logo design & complete brand identity support',
    ],
    image: '/assets/services/service-creative-services.jpg',
    packages: [
      {
        name: 'Creative Starter',
        badge: 'BEST FOR SMALL BUSINESSES',
        tagline: 'CORE DESIGN • BRANDING',
        price: '₹4,999',
        period: '/ month',
        idealFor: 'Small businesses starting their brand journey',
        timeline: 'Monthly Creative Retainer',
        features: [
          'Up to 10 designs / month',
          'Social media posts & story designs',
          'Festival & offer creatives',
          'Basic brand templates',
          '1 revision per design',
          'Delivery within 2–3 working days',
        ],
      },
      {
        name: 'Creative Professional',
        badge: 'BEST FOR GROWING BUSINESSES',
        popular: true,
        tagline: 'BRAND SYSTEM • CAMPAIGNS',
        price: '₹9,999',
        period: '/ month',
        idealFor: 'Growing businesses needing consistent high-quality designs',
        timeline: 'Monthly Creative Retainer',
        features: [
          'Up to 25 designs / month',
          'Social posts, carousels & stories',
          'Reel covers & thumbnails',
          'Festival & campaign creatives',
          'Custom brand-aligned designs',
          '2 revisions per design',
          'Priority delivery (1–2 working days)',
        ],
      },
      {
        name: 'Creative Premium',
        badge: 'BEST FOR ESTABLISHED BRANDS',
        tagline: 'FULL CREATIVE • AUTHORITY',
        price: '₹19,999',
        period: '/ month',
        idealFor: 'Brands wanting a complete creative design solution',
        timeline: 'Premium Creative Retainer',
        features: [
          'Up to 50 designs / month',
          'Premium posts, carousels & stories',
          'Reel editing & motion graphics',
          'Brochures, flyers & marketing assets',
          'Ad creatives for Meta & Google',
          'Logo & brand identity support',
          'Priority delivery & dedicated support',
        ],
      },
    ],
  },
  {
    num: '05',
    slug: 'social-media-marketing',
    name: 'Paid Advertising & Performance Marketing',
    tagline: 'Turn Clicks Into Customers.',
    desc: 'Data-driven ad campaigns that bring real leads, sales and business growth.',
    startingPrice: '₹6,999 / mo',
    timeline: 'Monthly Campaign Management',
    metricsHighlight: 'Data-Driven Targeting & Conversion Optimization',
    tags: ['Meta Ads', 'Google Ads', 'Lead Generation', 'Retargeting', 'Conversion Campaigns', 'A/B Testing'],
    capabilities: ['Facebook & Instagram Ads', 'Google Ads Campaigns', 'Audience & Lookalike Targeting', 'Ad Copywriting & Creatives', 'Conversion Tracking Setup', 'Weekly/Monthly Analytics'],
    coreDeliverables: [
      'Facebook, Instagram & Google Ads campaign architecture',
      '1 to multiple campaign objectives & advanced audience targeting',
      '2 to 5+ high-converting ad creatives with copywriting & strategy',
      'A/B testing, conversion tracking setup & dedicated monthly reports',
    ],
    image: '/assets/services/service-social-media-marketing.jpg',
    packages: [
      {
        name: 'Ads Starter',
        badge: 'BEST FOR SMALL BUSINESSES',
        tagline: 'FOUNDATION • LEAD GENERATION',
        price: '₹6,999',
        period: '/ month (+ Ad Spend)',
        idealFor: 'Small businesses starting with paid advertising',
        timeline: 'Monthly Campaign Management',
        features: [
          'Facebook & Instagram ad setup',
          '1 campaign objective',
          'Basic audience research',
          '2 ad creatives & ad copywriting',
          'Campaign monitoring',
          'Monthly performance report',
          'Email / WhatsApp support',
        ],
      },
      {
        name: 'Ads Professional',
        badge: 'BEST FOR GROWING BUSINESSES',
        popular: true,
        tagline: 'GROWTH • META + GOOGLE • CONVERSIONS',
        price: '₹12,999',
        period: '/ month (+ Ad Spend)',
        idealFor: 'Growing businesses focused on verified leads & sales',
        timeline: 'Monthly Performance Management',
        features: [
          'Facebook, Instagram + Google Ads',
          'Up to 3 campaign objectives',
          'Advanced audience targeting',
          '5 ad creatives (images/videos)',
          'Ad copy & strategy',
          'A/B testing & optimization',
          'Conversion tracking setup',
          'Detailed monthly report',
          '1 strategy call per month',
        ],
      },
      {
        name: 'Ads Premium',
        badge: 'BEST FOR ESTABLISHED BRANDS',
        tagline: 'SCALE • FULL FUNNEL • RETARGETING',
        price: '₹24,999',
        period: '/ month (+ Ad Spend)',
        idealFor: 'Businesses running continuous & advanced campaigns',
        timeline: 'Advanced Performance Management',
        features: [
          'Facebook, Instagram, Google & more',
          'Multiple campaign objectives',
          'Advanced audience & lookalike targeting',
          'Unlimited creative variations',
          'Full-funnel campaign strategy',
          'Retargeting & remarketing',
          'Landing page recommendations',
          'Weekly monitoring & analytics',
          'Dedicated account manager',
          '2 strategy calls per month',
        ],
      },
    ],
  },
  {
    num: '06',
    slug: 'social-media-management',
    name: 'Social Media Management (Organic & Content)',
    tagline: 'Consistent Content. Stronger Communities.',
    desc: 'Strategic social media management that builds your brand, grows your audience, and turns consistent content into meaningful business growth.',
    startingPrice: '₹7,999 / mo',
    timeline: 'Monthly Retainer Sprint',
    metricsHighlight: 'Consistent Content & Real Communities',
    tags: ['Content Strategy', 'Creative Design', 'Reels & Stories', 'Community Management', 'Analytics & Reporting'],
    capabilities: ['Platform Strategy (Up to 5)', 'Monthly Content Calendars', 'Reels & Story Production', 'Custom Branded Creatives', 'DM & Comment Management', 'Monthly Growth Reports'],
    coreDeliverables: [
      'Up to 2 to 5 social media platforms managed',
      '12 to 30+ posts and 4 to 8 custom edited reels per month',
      'Story planning, custom branded creatives, caption & hashtag strategy',
      'Community management, comment & DM support, and monthly performance reports',
    ],
    image: '/assets/services/service-social-media-management.jpg',
    packages: [
      {
        name: 'Starter',
        badge: 'BEST FOR SMALL BUSINESSES',
        tagline: 'FOUNDATION • BRAND CONSISTENCY',
        price: '₹7,999',
        period: '/ month',
        idealFor: 'Businesses starting their social media journey',
        timeline: 'Monthly Retainer',
        features: [
          'Up to 2 social media platforms',
          '12 posts / month',
          'Basic captions & hashtag research',
          'Content calendar & branded templates',
          'Basic community engagement',
          'Profile optimization guidance',
          'Monthly performance report',
          'Email / WhatsApp support',
        ],
      },
      {
        name: 'Professional',
        badge: 'BEST FOR GROWING BUSINESSES',
        popular: true,
        tagline: 'GROWTH • REELS & STORIES',
        price: '₹14,999',
        period: '/ month',
        idealFor: 'Growing brands wanting consistent engagement',
        timeline: 'Monthly Retainer',
        features: [
          'Up to 4 social media platforms',
          '20 posts / month',
          '4 reels / month',
          'Story content planning',
          'Custom branded creatives',
          'Caption & hashtag strategy',
          'Content calendar & trend research',
          'Basic comment & DM management',
          'Competitor content analysis',
          'Monthly performance report',
          '1 strategy call / month',
        ],
      },
      {
        name: 'Premium',
        badge: 'BEST FOR BRANDS BUILDING AUTHORITY',
        tagline: 'AUTHORITY • FULL OMNICHANNEL',
        price: '₹29,999',
        period: '/ month',
        idealFor: 'Brands wanting a strong & active authority presence',
        timeline: 'Monthly Retainer',
        features: [
          'Up to 5 social media platforms',
          '30+ posts / month',
          '8 reels / month',
          'Story planning & management',
          'Premium custom creatives',
          'Advanced content strategy',
          'Community management',
          'Comment & DM support',
          'Competitor analysis',
          'Influencer collaboration support',
          'Detailed monthly reporting',
          '2 strategy calls / month',
          'Priority support',
        ],
      },
    ],
  },
];

// Popular Creative Services • Individual Pricing (Need just one design? We've got you covered.)
export const CREATIVE_INDIVIDUAL_PRICING = [
  { name: 'Social Media Post', desc: 'Static creative', price: '₹299+', icon: 'post' },
  { name: 'Carousel Design', desc: 'Multi-slide visual', price: '₹999+', icon: 'carousel' },
  // { name: 'Instagram Story', desc: 'Vertical creative', price: '₹199+', icon: 'story' },
  // { name: 'Reel Editing', desc: 'Short video edit', price: '₹799+', icon: 'reel' },
  { name: 'YouTube Thumb', desc: 'High-click visual', price: '₹299+', icon: 'youtube' },
  { name: 'Brochure Design', desc: 'Print-ready', price: '₹1,999+', icon: 'brochure' },
  { name: 'Flyer Design', desc: 'Promo flyer', price: '₹999+', icon: 'flyer' },
  { name: 'Logo Design', desc: 'Brand mark', price: '₹599+', icon: 'logo' },
  { name: 'Brand Identity', desc: 'Visual direction', price: '₹14,999+', icon: 'identity' },
  { name: 'Print & Marketing', desc: 'Banners & ads', price: 'Custom', icon: 'print' },
  { name: 'Ad Creative', desc: 'Meta & Google', price: '₹499+', icon: 'ad' },
  // { name: 'Campaign Set', desc: 'Launch visuals', price: '₹2,999+', icon: 'campaign' },
];

// Process Steps (4-Step Connected Timeline)
export const PROCESS_STEPS = [
  {
    num: '01',
    title: 'Discover',
    desc: 'Understand the business, users, and goals. Deep discovery, competitive audits, and honest diagnosis.',
  },
  {
    num: '02',
    title: 'Plan',
    desc: 'Create a clear strategy and architectural roadmap. Scope, tech stack, timeline, and measurable milestones.',
  },
  {
    num: '03',
    title: 'Build',
    desc: 'Design and develop with precision. Iterative sprints, senior craftsmanship, and transparent reviews.',
  },
  {
    num: '04',
    title: 'Grow',
    desc: 'Launch, improve, and scale. Monitoring, conversion optimization, and long-term strategic partnership.',
  },
];

// Why Skalorix (Why Skalorix Feels Different)
export const WHY_POINTS = [
  {
    icon: 'heart-handshake',
    title: 'Human-centered thinking',
    desc: 'We design for people first. Every interaction is tested against real human behavior, clarity, and accessibility.',
  },
  {
    icon: 'layers',
    title: 'Scalable technology',
    desc: 'Modular architecture, clean code, and cloud-native foundations engineered to support your long-term business growth.',
  },
  {
    icon: 'eye',
    title: 'Transparent collaboration',
    desc: 'Regular updates, shared ownership, and direct communication. You see progress, challenges, and decisions in real time.',
  },
  {
    icon: 'shield-check',
    title: 'Quality-driven execution',
    desc: 'Senior reviews, performance budgets, and rigorous testing ensure your product launches with absolute polish.',
  },
  {
    icon: 'infinity',
    title: 'Long-term partnership',
    desc: 'We stay beyond launch. Continuous optimization, ongoing support, and strategic guidance as your business expands.',
  },
];

// Featured Project
export const PROJECTS = [
  {
    id: 1,
    name: 'SNPIT Official Campus Mobile App',
    category: 'Cross-Platform Mobile App — Flutter & Dart',
    client: 'S. N. Patel Institute of Technology',
    tagline: 'Empowering Campus Connectivity & Academic Workflow',
    description: 'An official cross-platform mobile application engineered for S. N. Patel Institute of Technology using Flutter & Dart. Delivers a native 60fps mobile experience across Android & iOS, synchronizing real-time official notices, academic timetables, mid-sem exam schedules, attendance analytics, and faculty directories in one unified, calm, and performance-driven mobile ecosystem.',
    year: '2026',
    metrics: [
      { label: 'Timeline', value: '8 Weeks' },
      { label: 'Engine', value: 'Flutter • Dart' },
      { label: 'Platform', value: 'Android & iOS' },
    ],
    tags: ['Flutter', 'Dart', 'Cross-Platform', 'Mobile App', 'Campus ERP', 'UI/UX Design', 'Real-Time Sync'],
  },
];

// Testimonials
export const TESTIMONIALS = [
  {
    quote: 'Skalorix brought editorial clarity and technological polish to our campus platform. The experience is calm, reliable, and deeply appreciated by our students and faculty.',
    author: 'SNPIT Project Lead',
    role: 'Campus Academic Technology Lead',
    tag: 'Mobile App Ecosystem',
    rating: 5,
    highlight: 'No generic agency feel. Every detail was intentional, responsive, and crafted around real student workflow.',
  }
];

// Social Links
export const SOCIALS = [
  { label: 'Instagram', href: 'https://www.instagram.com/skalorixofficial/' },
  { label: 'LinkedIn', href: 'https://www.linkedin.com/company/skalorix' },
  { label: 'Twitter', href: 'https://x.com/skalorix' },
];
