// Brand Colors
export const COLORS = {
  deepForest: '#0F231B',
  forest2: '#132E24',
  forest3: '#1B3D2F',
  softOchre: '#C5A67A',
  goldLight: '#D9C19E',
  goldDeep: '#A68A62',
  ivory: '#FDFBF6',
  ivory2: '#F7F0E6',
  cream: '#EFE6D5',
  parchment: '#F8F4EA',
  stone: '#A69E93',
  charcoal: '#171D1A',
};

// Three.js colors (hex numbers)
export const THREE_COLORS = {
  deepForest: 0x0F231B,
  forest2: 0x132E24,
  softOchre: 0xC5A67A,
  goldLight: 0xD9C19E,
  parchment: 0xFDFBF6,
  stone: 0xA69E93,
  charcoal: 0x171D1A,
  black: 0x000000,
  white: 0xffffff,
};

// Navigation
export const NAV_ITEMS = [
  { label: 'Services', href: '#services' },
  { label: 'Work', href: '#work' },
  { label: 'About', href: '#about' },
  { label: 'Process', href: '#process' },
  { label: 'Why Us', href: '#why' },
  { label: 'Contact', href: '#contact' },
];

// Contact & Booking Details
export const CONTACT_INFO = {
  phone: '+91 94094 10260',
  whatsappNumber: '919409410260',
  calBookingUrl: 'https://cal.com/skalorix/30min',
  email: 'hello@skalorix.com',
  location: 'Surat, Gujarat, India',
};

// Services (6 Core Disciplines with rich deliverables and comprehensive package tiers)
export const SERVICES = [
  {
    num: '01',
    slug: 'web-development',
    name: 'Web Development',
    tagline: 'Digital Experiences That Perform.',
    desc: 'High-performance, SEO-ready web platforms engineered with modern frameworks, edge rendering, and obsessive attention to speed and craft.',
    startingPrice: '₹12,999',
    timeline: '7 - 10 Days Delivery',
    metricsHighlight: '99+ Lighthouse Performance & SEO Score',
    tags: ['React', 'Next.js', 'Performance', 'Full-Stack', 'Edge APIs', 'GSAP'],
    capabilities: ['UI/UX Design', 'Frontend Engineering', 'CMS Integration', 'E-Commerce', 'Performance Optimization', 'Responsive Layouts'],
    coreDeliverables: [
      'High-converting bespoke landing pages & multi-page corporate sites',
      'Ultra-fast load times (sub-second edge delivery & 95+ Core Web Vitals)',
      'CMS & headless architecture (easy blogging, content & product updates)',
      'WhatsApp API, CRM integration & dynamic lead generation funnels',
    ],
    image: '/assets/services/service-web-development.jpg',
    packages: [
      {
        name: 'Starter Web',
        badge: 'Quick Launch',
        price: '₹12,999',
        period: 'One-time investment',
        idealFor: 'Startups, local businesses & professionals needing a high-converting digital presence fast.',
        timeline: '7 - 10 Days',
        features: [
          'Up to 3 - 5 Bespoke Designed Pages',
          'Mobile-First & 100% Responsive Architecture',
          'Interactive WhatsApp Lead Capture Button',
          'Fast Contact & Inquiry Form Integration',
          'Google Search Console & Basic SEO Setup',
          'Ultra-Fast Hosting Setup & SSL Certificate',
          'Social Media & Google Maps Integration',
          '1 Month Post-Launch Maintenance & Support',
        ],
      },
      {
        name: 'Growth Corporate',
        badge: 'Most Popular',
        popular: true,
        price: '₹24,999',
        period: 'One-time investment',
        idealFor: 'Growing brands, agencies & businesses requiring dynamic authority and lead generation.',
        timeline: '14 - 18 Days',
        features: [
          'Up to 8 - 10 Custom Editorial Pages',
          'Dynamic CMS (Manage blogs, news & projects easily)',
          'Subtle GSAP Micro-Animations & Fluid Interactions',
          'Advanced On-Page Technical SEO & Schema Markup',
          'Speed Optimization (Sub-second load times & 95+ Score)',
          'Custom Contact Funnel with Email & WhatsApp Alerts',
          'Google Analytics 4 & Conversion Tracking Setup',
          '3 Months Priority Maintenance & Security Monitoring',
        ],
      },
      {
        name: 'Enterprise Scale',
        badge: 'Bespoke Craft',
        price: '₹44,999',
        period: 'One-time investment',
        idealFor: 'Established enterprises, D2C brands & premium companies wanting flagship digital craft.',
        timeline: '3 - 4 Weeks',
        features: [
          'Full Custom Digital Platform or E-Commerce Store',
          'E-Commerce Gateway (Razorpay/Stripe, Cart, Order Management)',
          '3D WebGL / Canvas Touches or Advanced Motion Choreography',
          'Headless Architecture with Edge CDN & Instant Caching',
          'Custom Lead Scoring, CRM Sync & Multi-Step Quotation Forms',
          'Full Accessibility (a11y) & Cross-Browser Precision',
          'Dedicated Project Sprint Lead & Code Ownership Handover',
          '6 Months Comprehensive Technical Support & SLA',
        ],
      },
    ],
  },
  {
    num: '02',
    slug: 'software-development',
    name: 'Software Development',
    tagline: 'Systems Built Around Your Business.',
    desc: 'Custom business software and application ecosystems that replace chaos with clarity. Scalable, modular, secure, and built to evolve.',
    startingPrice: '₹49,999',
    timeline: '3 - 4 Weeks Delivery',
    metricsHighlight: '99.9% Uptime & Cloud-Native Scalability',
    tags: ['Custom Architecture', 'Cloud APIs', 'Databases', 'Modular', 'Microservices', 'Node/Python'],
    capabilities: ['Web Applications', 'Mobile Development', 'API Design', 'Database Architecture', 'Cloud Infrastructure', 'Automation'],
    coreDeliverables: [
      'Tailored ERP, inventory, CRM, and workflow management systems',
      'Cross-platform mobile and web applications (Flutter / React Native / React)',
      'Enterprise database design with secure role-based permissions',
      'Third-party API integrations, webhook automations & cloud deployments',
    ],
    image: '/assets/services/service-software-development.jpg',
    packages: [
      {
        name: 'MVP Prototype',
        badge: 'Validation Sprint',
        price: '₹49,999',
        period: 'Project investment',
        idealFor: 'Entrepreneurs & innovators testing new product concepts with real users.',
        timeline: '3 - 4 Weeks',
        features: [
          'Core MVP Feature Engineering (Web or Mobile)',
          'User Authentication & Role Management (JWT/OAuth)',
          'Interactive Admin Dashboard & Data Tables',
          'PostgreSQL / Supabase / Firebase Cloud Database',
          'RESTful API Architecture & Clean Documentation',
          'Deployment on Cloud Server (AWS / DigitalOcean / Vercel)',
          'Complete Source Code Ownership & Git Repository',
          '2 Months Dedicated Bug-Fix Guarantee',
        ],
      },
      {
        name: 'Business ERP / SaaS',
        badge: 'Most Popular',
        popular: true,
        price: '₹99,999',
        period: 'Project investment',
        idealFor: 'Textile, manufacturing, trading, and service businesses streamlining operations.',
        timeline: '6 - 8 Weeks',
        features: [
          'Comprehensive Custom ERP or SaaS Web Application',
          'Multi-Tier Role Access (Admin, Manager, Staff, Client)',
          'Automated Invoicing, GST Billing & PDF Generation',
          'Inventory Tracking / Order Lifecycle / Real-Time Sync',
          'Automated WhatsApp & Email Notifications via Webhooks',
          'Data Export (Excel/CSV) & Executive BI Analytics Dashboards',
          'Secure Daily Automated Cloud Backups',
          '4 Months Maintenance & System Training Sessions',
        ],
      },
      {
        name: 'Enterprise Cloud System',
        badge: 'Full Scale',
        price: '₹1,89,999+',
        period: 'Custom enterprise scope',
        idealFor: 'Large-scale organizations requiring high concurrency, custom mobile apps & bespoke cloud.',
        timeline: '10 - 12 Weeks',
        features: [
          'Cross-Platform Mobile App (Android & iOS) + Web Suite',
          'High-Concurrency Microservices Architecture',
          'AI-Powered Workflow Automation & Smart Reporting',
          'Custom Hardware / POS / Barcode / Third-Party Integrations',
          'Automated CI/CD Pipelines & Staging Environments',
          'Rigorous Security Testing & Data Encryption at Rest',
          'On-Premise or Private Cloud Infrastructure Setup',
          '1 Year SLA Support & Quarterly Technology Reviews',
        ],
      },
    ],
  },
  {
    num: '03',
    slug: 'search-engine-optimization',
    name: 'Search Engine Optimization',
    tagline: 'Be Found. Be Relevant.',
    desc: 'Technical SEO, search intelligence, and structured content architecture for compounding organic visibility — not tricks, but lasting authority.',
    startingPrice: '₹8,999',
    timeline: 'Monthly Retainer Sprint',
    metricsHighlight: 'Top 3 Google Organic Rankings & High Intent Leads',
    tags: ['Technical Audits', 'Keyword Strategy', 'Search Intelligence', 'Local SEO', 'Backlink Outreach'],
    capabilities: ['Technical Audits', 'Keyword Strategy', 'Content Optimization', 'Link Building', 'Local SEO', 'Analytics & Reporting'],
    coreDeliverables: [
      'Comprehensive technical site audit and Core Web Vitals speed tuning',
      'High-intent commercial keyword mapping targeting Gujarat & national buyers',
      'Google Business Profile (GMB) domination for local inquiries',
      'Authority link outreach and strategic digital PR backlink acquisition',
    ],
    image: '/assets/services/service-seo.jpg',
    packages: [
      {
        name: 'Local Authority SEO',
        badge: 'Local Growth',
        price: '₹8,999',
        period: 'per month',
        idealFor: 'Local businesses in Surat & Gujarat wanting to dominate local search & Google Maps.',
        timeline: 'Monthly Sprint',
        features: [
          'Google Business Profile (GMB) Full Audit & Optimization',
          'Targeting up to 15 High-Intent Local Keywords',
          'Local Citations & Directory Listings in India',
          'On-Page Optimization for Primary Service Pages',
          'Monthly Google Maps Review Strategy & Keyword Tracking',
          'Broken Link & Indexing Error Resolution',
          'Monthly Transparent Performance & Ranking Report',
        ],
      },
      {
        name: 'National Growth SEO',
        badge: 'Most Popular',
        popular: true,
        price: '₹18,499',
        period: 'per month',
        idealFor: 'Companies and D2C brands targeting state-wide and India-wide customer acquisition.',
        timeline: 'Monthly Sprint',
        features: [
          'Targeting up to 40 Strategic Commercial Keywords',
          'Deep Technical Site Audit & Schema Markup Injection',
          'Core Web Vitals & Mobile Usability Speed Engineering',
          'Competitor Keyword Gap Analysis & Interception',
          '2 High-Authority SEO Blog Articles / Landing Pages per month',
          'Quality Backlink Building & Contextual Link Outreach',
          'Bi-Weekly Keyword Movement & Traffic Analytics Updates',
        ],
      },
      {
        name: 'Market Dominance',
        badge: 'Authority Scale',
        price: '₹34,999',
        period: 'per month',
        idealFor: 'High-growth brands, e-commerce stores & enterprises striving to own page 1 of Google.',
        timeline: 'Monthly Sprint',
        features: [
          'Targeting 80+ Competitive High-Volume Keywords',
          'Programmatic SEO & Scalable Content Hub Architecture',
          'High-Domain Authority (DA 40+) Editorial Backlink Acquisition',
          'Conversion Rate Optimization (CRO) on Organic Entry Pages',
          'E-Commerce Product Schema, Rich Snippets & FAQ Optimization',
          'Continuous Rank Defense against Search Engine Algorithm Updates',
          'Dedicated SEO Strategist & Monthly Executive Zoom Strategy',
        ],
      },
    ],
  },
  {
    num: '04',
    slug: 'creative-services',
    name: 'Creative Services',
    tagline: 'Make People Remember.',
    desc: 'From distinct brand identity to editorial design systems and campaign visuals, we craft work that cuts through noise and builds lasting recognition.',
    startingPrice: '₹14,999',
    timeline: '10 - 14 Days Delivery',
    metricsHighlight: '100% Bespoke Vector Art & Cohesive Brand Equity',
    tags: ['Brand Identity', 'Editorial Design', 'Motion Art', 'Figma Systems', 'Vector Craft'],
    capabilities: ['Brand Identity', 'Visual Design', 'Motion Graphics', 'Campaign Creative', 'Packaging Design', 'Typography Direction'],
    coreDeliverables: [
      'Memorable logo suites (primary mark, secondary symbol & monogram)',
      'Editorial color palette, typography hierarchy & custom font rules',
      'Marketing stationery (business cards, letterheads, invoice templates)',
      'Complete brand guideline deck & ready-to-use vector assets',
    ],
    image: '/assets/services/service-creative-services.jpg',
    packages: [
      {
        name: 'Identity Essentials',
        badge: 'New Brand',
        price: '₹14,999',
        period: 'One-time investment',
        idealFor: 'New ventures & startups needing a bespoke, professional visual mark.',
        timeline: '10 - 12 Days',
        features: [
          '3 Distinct Creative Logo Directions & Concepts',
          'Primary Logo, Secondary Logo & Favicon / Social Monogram',
          'Curated Luxury Color Palette (Hex, RGB, CMYK Codes)',
          'Typography System & Font Pairing Guidelines',
          'Social Media Profile Avatar & Header Starter Kit',
          'Full Vector Source Files (.AI, .SVG, .EPS, .PNG, .PDF)',
          'Complete Copyright & Brand Ownership Handover',
        ],
      },
      {
        name: 'Complete Brand System',
        badge: 'Most Popular',
        popular: true,
        price: '₹29,999',
        period: 'One-time investment',
        idealFor: 'Growing companies seeking a cohesive, prestigious corporate identity.',
        timeline: '2 - 3 Weeks',
        features: [
          'Comprehensive Brand Identity Architecture (5 Concepts)',
          'Full Brand Guidelines Book (30+ Pages PDF Deck)',
          'Complete Stationery Suite (Business Card, Letterhead, Envelope)',
          'Digital Brand Collateral (Email Signature, Presentation Deck Template)',
          'Packaging or Merchandise Mockups & Guidelines',
          'Custom Iconography & Graphic Element Suite',
          'Figma Design Tokens & Source File Master Library',
        ],
      },
      {
        name: 'Product UI/UX Suite',
        badge: 'Digital Craft',
        price: '₹54,999',
        period: 'Project investment',
        idealFor: 'Tech startups & products requiring world-class web or mobile app UI/UX.',
        timeline: '3 - 5 Weeks',
        features: [
          'Complete Web or Mobile App UI/UX Experience Design',
          'User Persona Research & Interactive Information Architecture',
          'Low-Fidelity Wireframes to High-Fidelity Pixel-Perfect Screens',
          'Clickable Interactive Prototype in Figma for Stakeholder Demos',
          'Bespoke Micro-Interactions & Animation Specs',
          'Production-Ready Design System (Components, Variants, Auto-Layout)',
          'Developer Handover Session & Asset Export Package',
        ],
      },
    ],
  },
  {
    num: '05',
    slug: 'social-media-marketing',
    name: 'Social Media Marketing',
    tagline: 'Turn Attention Into Action.',
    desc: 'Strategic paid social campaigns that acquire qualified audiences, accelerate growth loops, and turn attention into measurable business outcomes.',
    startingPrice: '₹11,999',
    timeline: 'Monthly Retainer Sprint',
    metricsHighlight: '2.8x - 4.5x Targeted Return on Ad Spend (ROAS)',
    tags: ['Paid Media', 'Targeting', 'Conversion Optimization', 'Meta Ads', 'Funnel Design'],
    capabilities: ['Paid Social Campaigns', 'Audience Targeting', 'A/B Testing', 'Conversion Optimization', 'Performance Analytics', 'Growth Loops'],
    coreDeliverables: [
      'High-converting Meta (Instagram & Facebook) & Google ad campaigns',
      'Compelling ad creatives, video hooks & persuasive copywriting',
      'Advanced custom audience segmentation & pixel conversion tracking',
      'Retargeting funnels that turn curious clickers into paying customers',
    ],
    image: '/assets/services/service-social-media-marketing.jpg',
    packages: [
      {
        name: 'Launch Accelerator',
        badge: 'Starter Funnel',
        price: '₹11,999',
        period: 'per month (+ ad spend)',
        idealFor: 'Brands testing paid ads to generate their first stream of predictable leads.',
        timeline: 'Monthly Sprint',
        features: [
          'Meta Ads (Instagram & Facebook) Full Campaign Setup',
          'Meta Pixel & Conversion API (CAPI) Tracking Setup',
          'Audience Research & Competitor Ad Spying',
          '4 High-Converting Graphic/Carousel Ad Creatives per month',
          'Direct-Response Ad Copywriting & Headline Testing',
          'WhatsApp / Lead Form Optimization',
          'Monthly Ad Spend Budget Management up to ₹30,000',
          'Bi-Weekly Campaign Performance Reports',
        ],
      },
      {
        name: 'Growth Scale Campaign',
        badge: 'Most Popular',
        popular: true,
        price: '₹22,999',
        period: 'per month (+ ad spend)',
        idealFor: 'Businesses scaling customer acquisition with multi-stage ad funnels.',
        timeline: 'Monthly Sprint',
        features: [
          'Multi-Tier Meta + Google Ads Campaign Architecture',
          'Cold Traffic Acquisition + Warm Retargeting Funnels',
          '8 High-Performing Ad Assets (4 Statics + 4 Motion Video Ads)',
          'Hook & Angle Copywriting (Pain points, benefits, social proof)',
          'A/B Creative & Audience Split Testing',
          'Landing Page Conversion Rate Advisory',
          'Monthly Ad Spend Management up to ₹1,00,000',
          'Weekly Ad Optimization & WhatsApp Group Support',
        ],
      },
      {
        name: 'Omnichannel Dominance',
        badge: 'Scale Master',
        price: '₹39,999',
        period: 'per month (+ ad spend)',
        idealFor: 'High-volume businesses & direct-to-consumer brands scaling aggressively.',
        timeline: 'Monthly Sprint',
        features: [
          'Full-Funnel Omnichannel Ads (Meta, Google Search, YouTube)',
          '16 Bespoke Monthly Creatives (Reels, Motion Ads & Carousels)',
          'Dynamic Product Ads (DPA) & Abandoned Cart Recovery Funnels',
          'High-Ticket Lead Qualification Systems & CRM Integration',
          'Continuous ROAS Scaling & Creative Fatigue Refreshment',
          'Monthly Ad Spend Management up to ₹3,00,000+',
          'Dedicated Media Buyer & Weekly Strategy Zoom Calls',
        ],
      },
    ],
  },
  {
    num: '06',
    slug: 'social-media-management',
    name: 'Social Media Management',
    tagline: 'Build Consistency. Build Community.',
    desc: 'We cultivate your digital presence with intention — editorial content ecosystems, consistent brand voice, and genuine community engagement.',
    startingPrice: '₹9,999',
    timeline: 'Monthly Retainer Sprint',
    metricsHighlight: 'Daily Organic Visibility & Brand Recall',
    tags: ['Content Strategy', 'Community Growth', 'Brand Voice', 'Reels Production', 'Editorial Grid'],
    capabilities: ['Content Calendars', 'Community Management', 'Platform Strategy', 'Content Creation', 'Engagement Analysis', 'Brand Voice'],
    coreDeliverables: [
      'Strategic monthly content calendars aligned with business milestones',
      'High-aesthetic feed design, trending reels editing & storytelling carousels',
      'Active community engagement, comment responses & direct message triage',
      'Brand tone governance to ensure an elevated, trustworthy presence',
    ],
    image: '/assets/services/service-social-media-management.jpg',
    packages: [
      {
        name: 'Brand Consistency',
        badge: 'Essential Grid',
        price: '₹9,999',
        period: 'per month',
        idealFor: 'Businesses needing a clean, professional, and active social media presence.',
        timeline: 'Monthly Retainer',
        features: [
          '12 Curated Feed Posts (Static & Carousels) per month',
          '8 Interactive Stories with Polls & Engagement Prompts',
          'Monthly Content Calendar & Strategic Theme Planning',
          'Compelling Captions & Hashtag Research Strategy',
          'Consistent Aesthetic Matching Brand Color Palette',
          'Scheduled Publishing at Peak Audience Times',
          'Monthly Growth & Audience Engagement Report',
        ],
      },
      {
        name: 'Engaged Authority',
        badge: 'Most Popular',
        popular: true,
        price: '₹19,999',
        period: 'per month',
        idealFor: 'Brands that want to grow organic reach through high-retention Reels & engagement.',
        timeline: 'Monthly Retainer',
        features: [
          '16 Feed Posts + 8 Trending Reels (Custom Video Editing)',
          '15 Monthly Stories & Highlight Cover Design',
          'Trending Audio Research & Viral Hook Formulations',
          'Scriptwriting & Creative Direction for Founder/Product Videos',
          'Daily Community Management (Comments & DM Inquiries)',
          'Collaborative Giveaway or Milestone Campaign Strategy',
          'Bi-Weekly Performance Reviews & Strategy Tuning',
        ],
      },
      {
        name: '360 Digital Presence',
        badge: 'Full Omnichannel',
        price: '₹32,999',
        period: 'per month',
        idealFor: 'Companies establishing multi-channel industry leadership and personal branding.',
        timeline: 'Monthly Retainer',
        features: [
          '24 Premium Monthly Assets (12 High-Production Reels + 12 Carousels)',
          'Daily Active Stories & Highlight Updates',
          'Multi-Platform Management (Instagram + LinkedIn / Facebook)',
          'LinkedIn Founder Thought Leadership Post Ghostwriting',
          'Influencer Outreach & Local Surat/Gujarat Creator Collabs',
          'Proactive Community Building & Audience Interception',
          'Dedicated Social Media Manager & Real-Time WhatsApp Channel',
        ],
      },
    ],
  },
];

// Process Steps (4-Step Connected Timeline)
export const PROCESS_STEPS = [
  {
    num: '01',
    title: 'Discover',
    desc: 'Understand the business, users, and goals. Deep discovery, competitive audits, and honest diagnosis.',
  },
  {
    num: '02',
    title: 'Plan',
    desc: 'Create a clear strategy and architectural roadmap. Scope, tech stack, timeline, and measurable milestones.',
  },
  {
    num: '03',
    title: 'Build',
    desc: 'Design and develop with precision. Iterative sprints, senior craftsmanship, and transparent reviews.',
  },
  {
    num: '04',
    title: 'Grow',
    desc: 'Launch, improve, and scale. Monitoring, conversion optimization, and long-term strategic partnership.',
  },
];

// Why Skalorix (Why Skalorix Feels Different)
export const WHY_POINTS = [
  {
    icon: 'heart-handshake',
    title: 'Human-centered thinking',
    desc: 'We design for people first. Every interaction is tested against real human behavior, clarity, and accessibility.',
  },
  {
    icon: 'layers',
    title: 'Scalable technology',
    desc: 'Modular architecture, clean code, and cloud-native foundations engineered to support your long-term business growth.',
  },
  {
    icon: 'eye',
    title: 'Transparent collaboration',
    desc: 'Regular updates, shared ownership, and direct communication. You see progress, challenges, and decisions in real time.',
  },
  {
    icon: 'shield-check',
    title: 'Quality-driven execution',
    desc: 'Senior reviews, performance budgets, and rigorous testing ensure your product launches with absolute polish.',
  },
  {
    icon: 'infinity',
    title: 'Long-term partnership',
    desc: 'We stay beyond launch. Continuous optimization, ongoing support, and strategic guidance as your business expands.',
  },
];

// Featured Project
export const PROJECTS = [
  {
    id: 1,
    name: 'SNPIT Official Campus Mobile App',
    category: 'Cross-Platform Mobile App — Flutter & Dart',
    client: 'S. N. Patel Institute of Technology',
    tagline: 'Empowering Campus Connectivity & Academic Workflow',
    description: 'An official cross-platform mobile application engineered for S. N. Patel Institute of Technology using Flutter & Dart. Delivers a native 60fps mobile experience across Android & iOS, synchronizing real-time official notices, academic timetables, mid-sem exam schedules, attendance analytics, and faculty directories in one unified, calm, and performance-driven mobile ecosystem.',
    year: '2026',
    metrics: [
      { label: 'Timeline', value: '8 Weeks' },
      { label: 'Engine', value: 'Flutter • Dart' },
      { label: 'Platform', value: 'Android & iOS' },
    ],
    tags: ['Flutter', 'Dart', 'Cross-Platform', 'Mobile App', 'Campus ERP', 'UI/UX Design', 'Real-Time Sync'],
  },
];

// Testimonials
export const TESTIMONIALS = [
  {
    quote: 'Skalorix brought editorial clarity and technological polish to our campus platform. The experience is calm, reliable, and deeply appreciated by our students and faculty.',
    author: 'SNPIT Project Lead',
    role: 'Campus Academic Technology Lead',
    tag: 'Mobile App Ecosystem',
    rating: 5,
    highlight: 'No generic agency feel. Every detail was intentional, responsive, and crafted around real student workflow.',
  }
];

// Social Links
export const SOCIALS = [
  { label: 'Instagram', href: 'https://www.instagram.com/skalorixofficial/' },
  { label: 'LinkedIn', href: 'https://www.linkedin.com/company/skalorix' },
  { label: 'Twitter', href: 'https://x.com/skalorix' },
];
